version: 0.1
phases:
  build:
    commands:
      mvn -X verify sonar:sonar -Dsonar.projectKey=102048 -Dsonar.organization=JavaprojectAWS_ -Dsonar.host.url=https://sonarcloud.io/organizations/102048/projects -Dsonar.login=bba091f83c13e5d93f3c7b62712641c545aaf3b0
